language: node_js
node_js: 0.10

before_install: npm install -g grunt-cli
install: grunt build

script: grunt test

deploy:
  provider: heroku
  api_key:
    secure: c/wHTZAzJUgWBm1w7KLlEDq6o9a/tbgzaZctJ+SkwwpqEIAJPEEeFzteRDzcQgGIRsws+C3m/zzWvqoQMmIoKvgJoNyoObZQazUCImly6hQMOHO8kqLMvugzXlgf4msnanA2pV3ABgvMG/MnoWSHnSJ8jbn6g16f+tDROnky8aU=
  app: bitcoin-trade-guard
  skip_cleanup: true
