language: node_js
node_js:
  - "0.10"

install:
  - "npm install -g grunt-cli bower"
  - "npm install"
  - "bower install"

script:
  - "grunt test"
  - "grunt build"

deploy:
  provider: heroku
  api_key:
    secure: c/wHTZAzJUgWBm1w7KLlEDq6o9a/tbgzaZctJ+SkwwpqEIAJPEEeFzteRDzcQgGIRsws+C3m/zzWvqoQMmIoKvgJoNyoObZQazUCImly6hQMOHO8kqLMvugzXlgf4msnanA2pV3ABgvMG/MnoWSHnSJ8jbn6g16f+tDROnky8aU=
  app: bitcoin-trade-guard
  strategy: git
